[[quotes]]
text = "Co můžeš udělat dnes, neodkládej na zítra."
author = "Přísloví"

[[quotes]]
text = "Kdo dřív přijde, ten dřív mele."
author = "Přísloví"

[[quotes]]
text = "Bez práce nejsou koláče."
author = "Přísloví"

[[quotes]]
text = "Kolik jazyků umíš, tolikrát jsi člověkem."
author = "Přísloví"

[[quotes]]
text = "Devatero řemesel, desáté bída."
author = "Přísloví"

[[quotes]]
text = "Vrána k vráně sedá."
author = "Přísloví"

[[quotes]]
text = "Troufeme si na vlka, tak na ni ne."
author = "Přísloví"

[[quotes]]
text = "Jedna vlaštovka jaro nedělá."
author = "Přísloví"

[[quotes]]
text = "Kdo jinému jámu kopá, sám do ní padá."
author = "Přísloví"

[[quotes]]
text = "Mluviti stříbro, mlčeti zlato."
author = "Přísloví"

[[quotes]]
text = "Ranní ptáče dál doskáče."
author = "Přísloví"

[[quotes]]
text = "Trpělivost růže přináší."
author = "Přísloví"

[[quotes]]
text = "Cvičení dělá mistra."
author = "Přísloví"

[[quotes]]
text = "Láska prochází žaludkem."
author = "Přísloví"

[[quotes]]
text = "Neštěstí nikdy nespí."
author = "Přísloví"