[[quotes]]
text = "Bez pracy nie ma kołaczy."
author = "Przysłowie"

[[quotes]]
text = "Co nagle, to po angielsku."
author = "Przysłowie"

[[quotes]]
text = "Czego się Jaś nie nauczy, tego Jan nie będzie umiał."
author = "Przysłowie"

[[quotes]]
text = "Darowanemu koniowi nie zagląda się w zęby."
author = "Przysłowie"

[[quotes]]
text = "Dla chcącego nic trudnego."
author = "Przysłowie"

[[quotes]]
text = "Gdzie kucharek sześć, tam nie ma co jeść."
author = "Przysłowie"

[[quotes]]
text = "Jak sobie pościelesz, tak się wyśpisz."
author = "Przysłowie"

[[quotes]]
text = "Kto rano wstaje, temu Pan Bóg daje."
author = "Przysłowie"

[[quotes]]
text = "Nosił wilk razy kilka, ponieśli i wilka."
author = "Przysłowie"

[[quotes]]
text = "Nie chwal dnia przed zachodem słońca."
author = "Przysłowie"

[[quotes]]
text = "Prawdziwych przyjaciół poznaje się w biedzie."
author = "Przysłowie"

[[quotes]]
text = "Strzeżonego Pan Bóg strzeże."
author = "Przysłowie"

[[quotes]]
text = "Trafiona kula, zgubiona."
author = "Przysłowie"

[[quotes]]
text = "Ziarnko do ziarnka, bo mi się nie robi się."
author = "Przysłowie"

[[quotes]]
text = "Cierpliwość jest kluczem do sukcesu."
author = "Przysłowie"