# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Racoon Typper Contributors

[workspace]
resolver = "2"
members = [
    "crates/domain",
    "crates/core",
    "crates/data",
    "crates/resources",
    "crates/application",
    "crates/app",
]

[workspace.package]
version = "1.3.1"
edition = "2021"
license = "Apache-2.0"
authors = ["Racoon Typper Contributors"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"

# Workspace internal deps
racoon-domain = { path = "crates/domain" }
racoon-core = { path = "crates/core" }
racoon-data = { path = "crates/data" }
racoon-resources = { path = "crates/resources" }
racoon-application = { path = "crates/application" }

# Shared deps
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.10"
uuid = { version = "1", features = ["serde", "v7"] }

[profile.release]
strip = true
lto = "thin"
