# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Racoon Typper Contributors

[package]
name = "racoon-app"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
racoon-domain = { workspace = true }
racoon-core = { workspace = true }
racoon-data = { workspace = true }
racoon-resources = { workspace = true }
racoon-application = { workspace = true }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-clipboard-manager = "2"
reqwest = { version = "0.12", features = ["blocking", "json", "rustls-tls"], default-features = false }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
chrono = "0.4"
rusqlite = { version = "0.31", features = ["bundled"] }
image = { version = "0.25", default-features = false, features = ["png"] }

[build-dependencies]
tauri-build = { version = "2", features = [] }
