# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Racoon Typper Contributors

[package]
name = "racoon-application"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
chrono = { workspace = true }
racoon-core = { workspace = true }
racoon-domain = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
